'use client';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowLeft, Minus, Plus, Trash2, ShoppingBag } from 'lucide-react';
import { useCart } from '@/components/cart-provider';
import { formatINR } from '@/lib/cart';
import { WhatsAppLink } from '@/components/whatsapp-link';

export default function CartPage(){
 const {lines,hydrated,remove,quantity,total,hasEnquiry}=useCart();
 const itemsText=lines.map(line=>`${line.name} × ${line.quantity}${line.priceOnRequest?' (price on request)':` — ${formatINR((line.unitPrice||0)*line.quantity)}`}`).join('\n');
 const message=`Hello Poornima Furniture, please help me with this furniture enquiry:\n${itemsText}\n\nPlease confirm availability, final pricing and next steps.`;
 return <><section className="page-header"><div className="section-shell"><span className="eyebrow">YOUR SHORTLIST</span><h1>Your <em>cart.</em></h1><p>Keep the pieces you like together. Enquiry-priced items can be sent to the showroom for a quote.</p></div></section><section className="cart-section section-shell">{!hydrated?<div className="loading-block">Restoring your cart…</div>:!lines.length?<div className="empty-state"><div className="showroom-fallback-icon"><ShoppingBag/></div><h2>Your cart is taking a little breather.</h2><p>Browse the collection and add a piece you’d like to keep an eye on.</p><Link className="button button-dark" href="/catalogue">Explore the collection</Link></div>:<div className="cart-layout"><div className="cart-items">{lines.map(line=><div className="cart-row" key={line.productId}><Link href={`/catalogue/${line.slug}`} className="cart-row-image">{line.image?<Image src={line.image} alt={line.name} fill sizes="95px"/>:<div className="image-placeholder"><span>PF</span></div>}</Link><div><h3><Link href={`/catalogue/${line.slug}`}>{line.name}</Link></h3><p>{line.priceOnRequest||line.unitPrice===null?'Price on request':formatINR(line.unitPrice)}</p><div className="quantity-controls"><button onClick={()=>quantity(line.productId,line.quantity-1)} aria-label={`Decrease ${line.name} quantity`}><Minus size={13}/></button><span>{line.quantity}</span><button onClick={()=>quantity(line.productId,line.quantity+1)} aria-label={`Increase ${line.name} quantity`}><Plus size={13}/></button><button className="remove-button" onClick={()=>remove(line.productId)} aria-label={`Remove ${line.name}`}><Trash2 size={13}/> Remove</button></div></div><div className="cart-row-total">{line.priceOnRequest||line.unitPrice===null?'Quote needed':formatINR(line.unitPrice*line.quantity)}</div></div>)}</div><aside className="cart-summary"><h2>Summary</h2><div className="summary-line"><span>Items ({lines.reduce((s,l)=>s+l.quantity,0)})</span><span>{formatINR(total)}</span></div>{hasEnquiry&&<div className="summary-line"><span>Enquiry-priced items</span><span>Quote needed</span></div>}<div className="summary-line summary-total"><span>{hasEnquiry?'Priced items subtotal':'Subtotal'}</span><span>{formatINR(total)}</span></div><p>Delivery charges, final pricing and availability will be confirmed by the showroom. This cart does not collect payment.</p><WhatsAppLink message={message} label="Send enquiry to showroom"/><Link className="button button-outline" href="/catalogue"><ArrowLeft size={15}/> Continue browsing</Link></aside></div>}</section></>;
}
