'use client';
import { FormEvent, useMemo, useState } from 'react';
import Image from 'next/image';
import { Plus, Trash2, Eye, EyeOff, ExternalLink, X, Save } from 'lucide-react';
import type { Product } from '@/lib/types';

type Enquiry = {id:string;customer_name:string;phone:string;email:string|null;message:string;status:string;created_at:string;product:{name:string}|null};
const inputStyle={width:'100%'};
export function AdminDashboard({products:initialProducts,enquiries:initialEnquiries}:{products:Product[];enquiries:Enquiry[]}){
 const [products,setProducts]=useState<Product[]>(initialProducts);const [enquiries,setEnquiries]=useState<Enquiry[]>(initialEnquiries);const [tab,setTab]=useState<'products'|'enquiries'>('products');const [editing,setEditing]=useState<Product|null>(null);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 async function submitProduct(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setNotice('');const fd=new FormData(e.currentTarget);const priceStr=String(fd.get('price')||'').trim();const payload={name:String(fd.get('name')||''),slug:String(fd.get('slug')||''),description:String(fd.get('description')||''),price:priceStr?Number(priceStr):null,price_on_request:fd.get('price_on_request')==='on',featured:fd.get('featured')==='on',published:fd.get('published')==='on',thumbnail_url:String(fd.get('thumbnail_url')||'').trim()||null,images:String(fd.get('thumbnail_url')||'').trim()?[String(fd.get('thumbnail_url'))]:[],availability:String(fd.get('availability')||'available'),materials:String(fd.get('materials')||'').split(',').map(x=>x.trim()).filter(Boolean),finishes:String(fd.get('finishes')||'').split(',').map(x=>x.trim()).filter(Boolean),category_id:null};
 try{const res=await fetch('/api/admin/products',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{id:editing.id,...payload}:payload)});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not save product');if(editing)setProducts(old=>old.map(p=>p.id===editing.id?data.product:p));else setProducts(old=>[data.product,...old]);setNotice(editing?'Product updated.':'Product created.');setEditing(null);}catch(err){setNotice(err instanceof Error?err.message:'Could not save product.');}finally{setBusy(false);}}
 async function removeProduct(product:Product){if(!window.confirm(`Delete “${product.name}”? This cannot be undone.`))return;setNotice('');try{const res=await fetch(`/api/admin/products?id=${encodeURIComponent(product.id)}`,{method:'DELETE'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not delete product');setProducts(old=>old.filter(p=>p.id!==product.id));setNotice('Product deleted.');}catch(err){setNotice(err instanceof Error?err.message:'Could not delete product.');}}
 async function updateEnquiry(id:string,status:string){setNotice('');try{const res=await fetch('/api/admin/enquiries',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not update enquiry');setEnquiries(old=>old.map(e=>e.id===id?{...e,status}:e));setNotice('Enquiry status updated.')}catch(err){setNotice(err instanceof Error?err.message:'Could not update enquiry.')}}
 const activeCount=useMemo(()=>products.filter(p=>p.published).length,[products]);
 return <div><div style={{display:'flex',gap:8,flexWrap:'wrap',borderBottom:'1px solid var(--line)',paddingBottom:15,marginBottom:25}}><button className={`button ${tab==='products'?'button-dark':'button-outline'}`} onClick={()=>setTab('products')}>Products ({products.length})</button><button className={`button ${tab==='enquiries'?'button-dark':'button-outline'}`} onClick={()=>setTab('enquiries')}>Enquiries ({enquiries.length})</button><span style={{alignSelf:'center',marginLeft:'auto',fontSize:10,color:'var(--muted)'}}>{activeCount} published</span></div>
 {notice&&<p className="form-message" role="status" style={{marginBottom:18}}>{notice}</p>}
 {tab==='products'&&<><div className="admin-top"><div><h2 style={{fontFamily:'var(--serif)',fontSize:30,fontWeight:500,margin:0}}>Product catalogue</h2><p style={{fontSize:11,color:'var(--muted)',margin:'5px 0'}}>Manage the catalogue that customers see.</p></div><button className="button button-dark" onClick={()=>setEditing({id:'',name:'',slug:'',description:'',category_id:null,price:null,sale_price:null,price_on_request:true,images:[],thumbnail_url:null,materials:[],finishes:[],dimensions:null,availability:'available',customization:null,featured:false,published:false,model_url:null,seo_title:null,seo_description:null,created_at:'',updated_at:''})}><Plus size={16}/> New product</button></div>
 {editing&&<form className="admin-form" onSubmit={submitProduct}><div className="admin-top full"><h3 style={{fontFamily:'var(--serif)',fontSize:25,fontWeight:500,margin:0}}>{editing.id?'Edit product':'Create product'}</h3><button type="button" className="button button-outline" onClick={()=>setEditing(null)}><X size={15}/> Close</button></div><div className="field"><label htmlFor="p-name">Product name *</label><input className="input" style={inputStyle} id="p-name" name="name" defaultValue={editing.name} required minLength={2} maxLength={160}/></div><div className="field"><label htmlFor="p-slug">Slug *</label><input className="input" style={inputStyle} id="p-slug" name="slug" defaultValue={editing.slug} required pattern="[a-z0-9]+(-[a-z0-9]+)*"/></div><div className="field full"><label htmlFor="p-description">Description</label><textarea className="textarea" id="p-description" name="description" defaultValue={editing.description||''}/></div><div className="field"><label htmlFor="p-price">Price (INR; blank if not set)</label><input className="input" style={inputStyle} id="p-price" name="price" type="number" min="0" step="1" defaultValue={editing.price??''}/></div><div className="field"><label htmlFor="p-image">Thumbnail image URL</label><input className="input" style={inputStyle} id="p-image" name="thumbnail_url" type="url" defaultValue={editing.thumbnail_url||editing.images?.[0]||''}/></div><div className="field"><label htmlFor="p-materials">Materials (comma-separated)</label><input className="input" style={inputStyle} id="p-materials" name="materials" defaultValue={editing.materials?.join(', ')||''}/></div><div className="field"><label htmlFor="p-finishes">Finishes (comma-separated)</label><input className="input" style={inputStyle} id="p-finishes" name="finishes" defaultValue={editing.finishes?.join(', ')||''}/></div><div className="field"><label htmlFor="p-availability">Availability</label><select className="select" style={inputStyle} id="p-availability" name="availability" defaultValue={editing.availability||'available'}><option value="available">Available</option><option value="made_to_order">Made to order</option><option value="unavailable">Unavailable</option></select></div><div className="field full" style={{display:'flex',flexDirection:'row',flexWrap:'wrap',gap:22}}><label><input type="checkbox" name="price_on_request" defaultChecked={editing.price_on_request}/> Price on request</label><label><input type="checkbox" name="featured" defaultChecked={editing.featured}/> Featured</label><label><input type="checkbox" name="published" defaultChecked={editing.published}/> Published</label></div><div className="field full"><button disabled={busy} className="button button-dark"><Save size={15}/>{busy?'Saving…':'Save product'}</button></div></form>}
 <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>PRODUCT</th><th>PRICE MODE</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><strong>{p.name}</strong><br/><span style={{color:'var(--muted)'}}>/{p.slug}</span></td><td>{p.price_on_request||p.price==null?'Price on request':`₹${p.price.toLocaleString('en-IN')}`}</td><td><span className="badge">{p.published?'Published':'Draft'}</span></td><td><div style={{display:'flex',gap:7,flexWrap:'wrap'}}><button className="button button-outline" style={{minHeight:32,padding:'0 9px'}} onClick={()=>setEditing(p)}><Save size={13}/> Edit</button><Link className="button button-outline" style={{minHeight:32,padding:'0 9px'}} href={`/catalogue/${p.slug}`}><ExternalLink size={13}/> View</Link><button className="button button-outline" style={{minHeight:32,padding:'0 9px'}} onClick={()=>removeProduct(p)} aria-label={`Delete ${p.name}`}><Trash2 size={13}/></button></div></td></tr>)}</tbody></table>{!products.length&&<div className="loading-block">No products yet. Create your first product above.</div>}</div></>}
 {tab==='enquiries'&&<><h2 style={{fontFamily:'var(--serif)',fontSize:30,fontWeight:500}}>Customer enquiries</h2><p style={{fontSize:11,color:'var(--muted)'}}>Customer details are shown only to authenticated administrators.</p><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>DATE</th><th>CUSTOMER</th><th>ENQUIRY</th><th>STATUS</th></tr></thead><tbody>{enquiries.map(e=><tr key={e.id}><td>{new Date(e.created_at).toLocaleDateString('en-IN')}</td><td><strong>{e.customer_name}</strong><br/><a href={`tel:${e.phone}`}>{e.phone}</a>{e.email&&<><br/><a href={`mailto:${e.email}`}>{e.email}</a></>}</td><td>{e.product?.name&&<strong>{e.product.name}: </strong>}{e.message}</td><td><select className="select" aria-label={`Status for ${e.customer_name}`} value={e.status} onChange={ev=>updateEnquiry(e.id,ev.target.value)}><option value="new">New</option><option value="contacted">Contacted</option><option value="quoted">Quoted</option><option value="converted">Converted</option><option value="closed">Closed</option></select></td></tr>)}</tbody></table>{!enquiries.length&&<div className="loading-block">No enquiries have been received yet.</div>}</div></>}
 </div>;
}
