'use client';
import Image from 'next/image';
import { useState } from 'react';
import { X, ZoomIn } from 'lucide-react';

export function ProductGallery({ name, images }: { name: string; images: string[] }) {
 const [active, setActive] = useState(0); const [lightbox, setLightbox] = useState(false);
 return <><div className="product-main-image">{images[active] ? <button type="button" onClick={()=>setLightbox(true)} aria-label={`Open larger image of ${name}`} style={{position:'absolute',inset:0,width:'100%',height:'100%',padding:0,border:0,background:'none',cursor:'zoom-in'}}><Image src={images[active]} alt={`${name}, image ${active+1}`} fill priority sizes="(max-width:760px) 100vw, 45vw"/><span style={{position:'absolute',bottom:14,right:14,width:38,height:38,display:'grid',placeItems:'center',background:'var(--paper)'}}><ZoomIn size={18}/></span></button> : <div className="image-placeholder"><span>PF</span><small>Product photography will be added here</small></div>}</div>{images.length>1&&<div className="product-thumbs">{images.map((src,i)=><button className={`product-thumb ${active===i?'active':''}`} type="button" key={`${src}-${i}`} aria-label={`View image ${i+1}`} onClick={()=>setActive(i)}><Image src={src} alt={`${name} thumbnail ${i+1}`} fill sizes="80px"/></button>)}</div>}{lightbox&&<div role="dialog" aria-modal="true" aria-label={`${name} image viewer`} onClick={()=>setLightbox(false)} onKeyDown={e=>{if(e.key==='Escape')setLightbox(false)}} tabIndex={-1} autoFocus style={{position:'fixed',inset:0,zIndex:100,background:'rgba(20,19,17,.93)',display:'grid',placeItems:'center',padding:24}}><button onClick={()=>setLightbox(false)} aria-label="Close image viewer" style={{position:'absolute',right:22,top:22,background:'transparent',color:'white',border:0,cursor:'pointer'}}><X size={28}/></button>{images[active]&&<div style={{position:'relative',width:'min(100%,1000px)',height:'min(82vh,850px)'}}><Image src={images[active]} alt={name} fill sizes="100vw" style={{objectFit:'contain'}}/></div>}</div>}</>;
}
